import turtle
def base():
    base=turtle.Turtle()
    base.penup()
    base.setpos(-100,-100)
    base.pendown()
    base.color=("#000")
    base.begin_fill()
    for i in range(2):
        base.forward(200)
        base.right(90)
        base.forward(20)
        base.right(90)
    base.end_fill()
    base.hideturtle()
def pole():
    pole=turtle.Turtle()
    pole.penup()
    pole.setpos(-100,-100)
    pole.forward(30)
    pole.left(90)
    pole.color("Brown")
    pole.pendown()
    pole.begin_fill()
    for i in range(2):
        pole.forward(300)
        pole.right(90)
        pole.forward(10)
        pole.right(90)
    pole.end_fill()
    pole.hideturtle()
def flag():
    flag=turtle.Turtle()
    flag.penup()
    flag.setpos(-60,190)
    flag.pendown()
    flag.setpos(-60,190)
    flag.color("Orange")
    flag.begin_fill()
    for i in range(2):
        flag.forward(150)
        flag.right(90)
        flag.fd(100/3)
        flag.right(90)
    flag.end_fill()
    flag.penup()
    flag.setpos(-60,190+-2*(100/3))
    flag.pendown()
    flag.color("Green")
    flag.begin_fill()
    for i in range(2):
        flag.forward(150)
        flag.right(90)
        flag.fd(100/3)
        flag.right(90)
    flag.end_fill()
    flag.penup()
    flag.setpos(-60,190)
    flag.pendown()
    flag.color("#000")
    for i in range(2):
        flag.forward(150)
        flag.right(90)
        flag.fd(100)
        flag.rt(90)
    flag.penup()
    flag.right(90)
    flag.fd(100/3)
    flag.left(90)
    flag.pendown()
    flag.fd(150)
    flag.penup()
    flag.bk(150)
    flag.rt(90)
    flag.fd(100/3)
    flag.lt(90)
    flag.pendown()
    flag.fd(150)
    flag.hideturtle()
def chakra():
    c=turtle.Turtle()
    c.penup()
    c.setpos(-60+(150/2),175-(100/2))
    c.color("Blue")
    c.pendown()
    c.circle(12)
    c.left(90)
    c.penup()
    c.forward(15)
    c.pendown()
    def lines():
        def sqr():
            for i in range(4):
                c.pensize(0.2)
                c.fd(12)
                c.right(90)
        for i in range(1,25):
            c.speed(10)
            c.right(360/24)
            sqr()
    lines()
    c.hideturtle()
def txt():
    t=turtle.Turtle()
    t.penup()
    t.setpos(0,-160)
    t.pendown()
    t.write("India Flag",align="Center",font=("Arial",24,"bold"))
    t.hideturtle()

    

base()
pole()
flag()
chakra()
txt()



turtle.done()