import turtle
turtle.speed(5)
turtle.pensize(10)
turtle.color("Red")
turtle.circle(100)
turtle.color("yellow")
turtle.circle(90)
turtle.color("pink")
turtle.circle(80)
turtle.color("cyan")
turtle.circle(70)
turtle.color("magenta")
turtle.circle(60)
turtle.color("violet")
turtle.circle(50)
turtle.color("blue")
turtle.circle(30)
turtle.color("green")
turtle.circle(10)

turtle.exitonclick()