import math
import turtle
def game():
    base=turtle.Turtle()
    base.color("black")
    base.pensize(10)
    base.forward(100)
    base.penup()
    base.right(90)
    base.forward(3)
    base.pendown()
    base.right(90)
    base.forward(100)
    base.penup()
    base.right(90)
    base.forward(3)
    base.right(90)
    base.forward(10)
    base.left(90)
    base.pendown()
    base.color("brown")
    base.forward(130)
    base.penup()
    base.backward(15)
    base.right(90)
    base.pendown()
    base.forward(70)
    base.penup()
    base.backward(5)
    base.right(90)
    base.pensize(5)
    base.pencolor("orange")
    base.pendown()
    base.forward(25)
    man=base
    man.color("black", "yellow")
    man.begin_fill()
    man.right(90)
    man.circle(10)
    man.end_fill()
    man.penup()
    man.circle(10,180)
    man.speed(5)
    for i in [45,90,135]:
        man.pendown()
        man.right(i)
        man.forward(20)
        man.penup()
        man.backward(20)
        man.left(i)
    man.right(90)
    man.penup()
    man.forward(20)
    man.left(90)
    for i in [45,135]:
        man.pendown()
        man.right(i)
        man.forward(20)
        man.penup()
        man.backward(20)
        man.left(i)
    pen=man
    pen.penup()
    pen.right(90)
    pen.forward(100)
    pen.right(90)
    pen.forward(70)
    pen.left(180)
    pen.write("You Lose", move=True, align='left', font=('Roboto',15,'normal'))
    pen.hideturtle()

    turtle.done()
game()